### ISSUE TITLE
Some configurations are missing

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-mountain-area#11]
According to the Briefing sent some configurations of the web component on the web component store are missing.

In particular actually for a web component store user are missing the following configuration opportunity:
- [x] configure the area to be shown (e.g. ski area, ski region, municipality, etc.). In this case the user should input one or more ID of the areas that wants to show
- [x] activate/deactivate the different winter activities available;
- [x] activate/deactivate the “get directions” button. This button could redirect for example to google maps.

@GnuRant

**Comment by lcfd** [comment]
Hi, @sseppi @Piiit point 1 and 3 are in PR.
Point 2 is still on hold due to filter level decisions.

cc @GnuRant

**Comment by Piiit** [comment]
@lcfd @GnuRant
We decided to always take the categories from the API, and always do the call and not hardcode them inside JS. Winter activities should be configurable, that means give a list which should be shown (whitelisting).

**Comment by lcfd** [comment]
@Piiit 
Ok, which endpoint do I have to use?

**Comment by sseppi** [comment]
@lcfd @GnuRant configuration of Get Direction doesn't work once activated the Get Direction in the Web component doesn't appear the "Get Direction" button once one Activity/POI is selected.

**Comment by Piiit** [comment]
@lcfd @GnuRant This feature works, but the store integration had a wrong configuration. So on your side there is nothing to do here.

@dulvui You need to change the type of disablePOIDirections and similar filters into "null" (not "bool"), since bool would generate disablePOIDirections=true or disablePOIDirections=false and null-types just add the key without any value...

**Comment by dulvui** [comment]
Fixed for disablePOIDirections and disableMeteo and tested in webstore: it's working.
