### ISSUE TITLE
Selecting a small radius centered at Bolzano results in 2 filters shown, even if none has been selected

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-mountain-area#13]

**Comment by lcfd** [comment]
@gnurant

**Comment by lcfd** [comment]
@Piiit Hi, can you provide me the configuration that you are using and if you can a  screen with the highlighted problem.
It's a bit complicated to understand the problem.
(1 filter shown it's fine because the radius is a filter)

cc @gnurant

**Comment by sseppi** [comment]
@lcfd here you can find a screeschot of the web component including the configurationwe are using.
![Schermata da 2021-02-09 18-33-10](https://user-images.githubusercontent.com/7909989/107403550-87a9e900-6b05-11eb-91af-92812cf81f21.png)
