### ISSUE TITLE
As a Web component Store manager I want to have the Mountain Area Web Component online

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-mountain-area#2]
@sseppi, done please test...

@lcfd See same issues as in https://github.com/noi-techpark/webcomp-gastronomies/issues/2

**Comment by sseppi** [comment]
The link to the component on our testing environment:

https://webcomponents.opendatahub.testingmachine.eu/webcomponent/430eead9-0bbc-4832-b4c0-78236d77a36b

**Comment by lcfd** [comment]
@sseppi @Piiit

This specific issue should be done

cc @GnuRant

**Comment by Piiit** [comment]
@lcfd @GnuRant It is done on your side, just an internal issue for me to put it online after our development has been completed
