### ISSUE TITLE
 The web componet doesnt use the coordinates input as configuration.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-mountain-area#4]
If I change the GPS coordinate of the`map centre (```currentLocation="{ 'lat': 46.31, 'lng': 11.26 }"```) of the map the web component doesn't change map centre even if in the code snippet the coordinates are properly seen.

It seems that the ```currentLocation``` parameter isn't properly managed by the web component store since, if I try the external view in the URL it seems to be ecoded wrong ```currentLocation="{ 'lat'%3A 46.31%2C 'lng'%3A 11.26 }"```.

@GnuRant

**Comment by lcfd** [comment]
@sseppi

As said in call this is a problem with the web component store way of use HTML parameters.
This issue is linked to the decision of maintain this semantic lit-element w.c. way or split the parameter in two.

cc @GnuRant

**Comment by Piiit** [comment]
@lcfd @GnuRant We decided to use separate attributes for lat and long with simple numbers as type, and remove currentLocation.

**Comment by sseppi** [comment]
@lcfd as you can see in the screeshot the web component does not uses the coordinates in the configuration but remais centered in Bolzano.
![Schermata da 2021-02-09 18-49-17](https://user-images.githubusercontent.com/7909989/107405591-c80a6680-6b07-11eb-8191-d874328fc9ad.png)

**Comment by lcfd** [comment]
@Piiit The issue is about not working parameters so for the refactor of the parameters we will need a new issue
@sseppi I found the error, and fixed. I'll move the issue to "To review". 
The PR: https://github.com/noi-techpark/webcomp-mountain-area/pull/17
