### ISSUE TITLE
The possibility to select one or more ski area to be shown is missing

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-mountain-area#8]
In the configuration is missing the possibility to input one or more ski area IDs in order to show only a subset of selected ski areas. In case of epty list all ski areas should be shown.

**Comment by sseppi** [comment]
See issue #11

**Comment by lcfd** [comment]
@sseppi 

Assign the issue  to me, for some mysterious reasons I can't modify the Assignees.

cc @gnurant

**Comment by sseppi** [comment]
> @sseppi
> 
> Assign the issue to me, for some mysterious reasons I can't modify the Assignees.
> 
> cc @GnuRant

@lcfd  Done
